#!/usr/bin/env python

import argparse
import os
import textwrap
from urllib.parse import urlparse

parser = argparse.ArgumentParser(description=textwrap.dedent('''
    Opens an OpenStack Gerrit review URL in vim. For example, given
    https://review.opendev.org/c/openstack/nova/+/764482/1/nova/utils.py#365
    opens nova/utils.py on line 365. Line numbers are optional.
    '''))
parser.add_argument('url', help='Gerrit URL')
args = parser.parse_args()

parse_result = urlparse(args.url)
# Using
# https://review.opendev.org/c/openstack/nova/+/764482/1/nova/utils.py#365 as
# an example.
path = parse_result.path     # '/c/openstack/nova/+/764482/1/nova/utils.py'
tokens = path.split('/')[7:] # ['nova', 'utils.py']
filename = '/'.join(tokens)  # 'nova/utils.py'
tokens = path.split('/')

line_number = parse_result.fragment # '365'

if line_number:
    os.execlp('vim', 'vim', '+%d' % int(line_number), filename)
else:
    os.execlp('vim', 'vim', filename)
